// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type RequestData struct {
	Data       *Data       `json:"Data"`
	Extensions *Extensions `json:"Extensions"`
}

type Data struct {
	NumberOfRequests *int `json:"NumberOfRequests"`
}

type Extensions struct {
	Status     *int    `json:"Status"`
	Message    *string `json:"Message"`
	XWaitTill  *string `json:"X_Wait_Till"`
	XRateLimit *int    `json:"X_Rate_Limit"`
}
