// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Disecturlpath struct {
	Scheme            *string `json:"scheme"`
	Topleveldomain    *string `json:"topleveldomain"`
	Secondleveldomain *string `json:"secondleveldomain"`
}

type Urlpath struct {
	URL *string `json:"URL"`
}
